### ISSUE TITLE
sequenceA in day4?

### ISSUE THREAD

**Issue by gitonthescene** [amalloy/aoc-2021#1]
Hi, I'm new to Haskell and so am enjoying reading through your solutions (which popped up in a Google search) and comparing them to mine.  I appreciate that you might not be interested in my kibitzing, though.  If you close this issue with no comment, I'll understand.

In day4 you use [`sequenceA b`](https://github.com/amalloy/aoc-2021/blob/main/day04/src/Main.hs#L45) to generate combinations to check if there is a winning board.  I think this produces too many combinations, since you're only interested in straight lines on the board.  I believe you want [transpose](https://hackage.haskell.org/package/base-4.16.0.0/docs/Data-List.html#v:transpose).

If you don't mind me asking, I'm curious to know how long you've been programming in Haskell?

**Comment by amalloy** [comment]
You can hear my detailed thoughts on YouTube; I've linked the channel from this repository's README. 

But in brief, `sequenceA` is correct. You would be right if my Board were a `[[Maybe a]]`, but it is a `Five (Five (Maybe a)))`, and `Five`'s Applicative instance is zippy, not loopy (it's like a ZipList constrained to exactly five elements). Try it in GHCI and see for yourself!

I dunno, I first started picking up Haskell around a decade ago, after a couple years of Clojure. I don't really do any serious programming in it, but I've done Advent of Code in Haskell since the beginning.

**Comment by gitonthescene** [comment]
Thanks for the quick reply.  I’ll have to think on it a bit.  FWIW, this AoC is my first time coding in Haskell after reading through LYAH and poking around various papers and blogs.  My code leans heavily on folds as I’m not yet familiar with the  heavy machinery.  I was only curious about your experience for a reference point.  Thanks for the pointer to your YouTube channel, too.  I’ll close this issue now.

**Comment by gitonthescene** [comment]
FWIW, I think I get it now.  What’s interesting to me is that [winningRow](https://github.com/amalloy/aoc-2021/blob/main/day04/src/Main.hs#L47) is polymorphic and operates on a `Board` on the one hand and then a `[Five Int]` on the other.  I think it works because both `Board` and `[]` are `Traversable`.

**Comment by amalloy** [comment]
Sorry, no. There are no lists in my Board. In this case, `sequenceA :: Five (Five (Maybe a)) -> Five (Five (Maybe a))`. So in both cases, `winningRow` is being called with a `Five (Five (Maybe a))`. For example, in GHCI we have:

```
*Main> let row = Five 1 2 3 4 5; b = Five row row row row row in (b, sequenceA b)
(Five (Five 1 2 3 4 5) (Five 1 2 3 4 5) (Five 1 2 3 4 5) (Five 1 2 3 4 5) (Five 1 2 3 4 5),
 Five (Five 1 1 1 1 1) (Five 2 2 2 2 2) (Five 3 3 3 3 3) (Five 4 4 4 4 4) (Five 5 5 5 5 5))
```

**Comment by gitonthescene** [comment]
Ah, I thought [sequenceA](https://hackage.haskell.org/package/base-4.16.0.0/docs/Prelude.html#v:sequenceA) returned a list in the applicative but it returns the traversable in the applicative.  So because Five is both it returns a new `Board`.

**Comment by amalloy** [comment]
Technically a new `Five (Five (Maybe a))`, since we've already unwrapped the `Board` newtype. But close enough.
